export * from './actor-image/actor-image.component';
export * from './block/block.component';
export * from './card/card.component';
export * from './poster-image/poster-image.component';
export * from './typography/typography.component';
export * from './star-rate/star-rate.component';
export * from './rate-button/rate-button.component';
export * from './back-button/back-button.component';
export * from './tab/tab.component';
